<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Application (NOT Library) -->
    <OutputType>WinExe</OutputType>

    <!-- WPF -->
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>

    <!-- Portable EXE -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

    <!-- Stability -->
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <!-- Copy config file -->
  <ItemGroup>
    <Content Include="Config\excel_mapping.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
  </ItemGroup>

</Project>
